name: Deploy Content to loganalytics-workspace [bb87ef19-63de-4441-a12b-ebadfde77b1e]
# Note: This workflow will deploy everything in the root directory.
# To deploy content only from a specific path (for example SentinelContent):
#   1. Add the target path to the "paths" property like such
#    paths:
#    - 'SentinelContent/**'
#    - '!.github/workflows/**'
#    - '.github/workflows/sentinel-deploy-bb87ef19-63de-4441-a12b-ebadfde77b1e.yml'
#   2. Append the path to the directory environment variable below
#       directory: '${{ github.workspace }}/SentinelContent'

on: 
  push:
    branches: [ main ]
    paths:
    - '**'
    - '!.github/workflows/**'  # this filter prevents other workflow changes from triggering this workflow
    - '.github/workflows/sentinel-deploy-bb87ef19-63de-4441-a12b-ebadfde77b1e.yml'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'sentinel'
      workspaceName: 'loganalytics-workspace'
      workspaceId: '9c76f468-ab2d-493c-8aa9-b1a44d89348b'
      directory: '${{ github.workspace }}'
      cloudEnv: 'AzureCloud'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_bb87ef1963de4441a12bebadfde77b1e }}
      contentTypes: 'Workbook,Playbook'
      branch: 'main'
      sourceControlId: 'bb87ef19-63de-4441-a12b-ebadfde77b1e'
      rootDirectory: '${{ github.workspace }}'
      githubAuthToken: ${{ secrets.GITHUB_TOKEN }}
      smartDeployment: 'true'
      trigger : 'workflow'
      tenantId : ${{ secrets.tenant_id }}
      applicationId: ${{ secrets.application_id }}
      applicationSecret : ${{ secrets.application_secret }}
      workspaceKey : ${{ secrets.workspace_key}}
      username : ${{ secrets.username }}


    steps:

    - name: Login to Azure (Attempt 1)
      continue-on-error: true
      id: login1
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_bb87ef1963de4441a12bebadfde77b1e }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 1 failed
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      run: powershell Start-Sleep -s 30
    
    - name: Login to Azure (Attempt 2)
      continue-on-error: true
      id: login2
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login1.outcome=='failure' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_bb87ef1963de4441a12bebadfde77b1e }}
        enable-AzPSSession: true

    - name: Wait 30 seconds if login attempt 2 failed
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure' }}
      run: powershell Start-Sleep -s 30
    
    - name: Login to Azure (Attempt 3)
      continue-on-error: false
      id: login3
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' && steps.login2.outcome=='failure'  }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_bb87ef1963de4441a12bebadfde77b1e }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v3
     
    - name: replace 
      run: get-content playbooks/azuredeploy.json | %{$_ -replace "configtenantId","5fa08688-b200-4f9d-aefa-d604d7c550fa"} | set-content -path playbooks/azuredeploy.json
    
    - name: Deploy Content to Azure Sentinel
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ github.workspace }}//.github/workflows/azure-sentinel-deploy-bb87ef19-63de-4441-a12b-ebadfde77b1e.ps1